### ISSUE TITLE
Clock messages?

### ISSUE THREAD

**Issue by anselanza** [dinchak/node-easymidi#11]
I see an example for receiving clock messages, but no data appears to be included with these, and clock type messages appear to be ignored in the code?

**Comment by dinchak** [comment]
hello!

midi clock messages don't really have any data attached to them, they are treated as a pulse.  think of them like mouse click events attached to an element on a web page.  that isn't even a great analogy, because mouse click events do have some position information, etc.  but you're generally more interested in if/when they fire, not the data associated (in the case of midi clock there really isn't any data).

see: https://en.wikipedia.org/wiki/MIDI_beat_clock

if you'd like to keep track of song position, generally you will want to count the midi clock pulses.  the rate is 48 per bar.  you'll want to set the counter back to 0 on a 'reset' message, and override the counter on a 'position' message.  hope this clears things up!

**Comment by anselanza** [comment]
Ah, I think I understand better now, thanks!
